version: '2'
services:
    tktt-app:
        image: tktt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://tktt-mariadb:3306/tktt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tktt-elasticsearch:9300
        ports:
            - 8080:8080
    tktt-mariadb:
        extends:
            file: mariadb.yml
            service: tktt-mariadb
    tktt-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tktt-elasticsearch
